# Generated by Django 4.0.6 on 2023-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_message_options_userfollowing_userfollowers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollowers',
            constraint=models.UniqueConstraint(fields=('myFollower', 'follower'), name='unique_myFollower_follower'),
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('myFollowing', 'following'), name='unique_myFollowing_following'),
        ),
    ]
