# Generated by Django 4.0.6 on 2023-08-08 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_userfollowers_unique_followers_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subscribe',
            field=models.ManyToManyField(blank=True, related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
